### PR TITLE
S-K-M fixes

### PR DESCRIPTION
**Pull request by robinwhittleton**
…and update boilerplate to latest versions.

### CODE REVIEW

**Comment by acabal** [comment]
This raises an issue. We remove `inflorescence` because it's not in the body text. But there is actually a glossary entry for that term, and it's because the term occurs in the glossary itself (in the definition for `compositous plants`). m-070 explicitly excludes the glossary so this becomes an error.

I think the way to fix this is to make m-070 include the glossary in its checks, but only to check the contents of `<dd>` elements. You can test this by using xpath to select dd elements and test them with regex in the xpath itself. Search lint for `re:test(` for an example.

**Comment by robinwhittleton** [comment]
Sounds like a plan.

**Comment by robinwhittleton** [comment]
https://github.com/standardebooks/tools/pull/441 fixes that.

**Comment by robinwhittleton** [comment]
I’ve reworked this PR to account for glossdefs.

**Pull request merged**
